"""Reproducible data cleaning pipeline transforming raw export into analytical dataset."""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import numpy as np
import pandas as pd

from src.cleaning.category_normalization import CategoryNormalizer, normalize_categories
from src.quality.date_validation import DateValidator
from src.quality.duplicates import DuplicateDetector
from src.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class CleaningPipelineResult:
    """Outcome summary and datasets generated by the cleaning pipeline."""

    cleaned_df: pd.DataFrame
    quarantined_df: pd.DataFrame
    initial_rows: int
    final_rows: int
    deduplicated_rows_count: int
    quarantined_rows_count: int
    modifications_applied: int


class CleaningPipeline:
    """Production data cleaning transformer enforcing reproducibility and raw immutability."""

    def __init__(
        self,
        reference_date: pd.Timestamp = pd.Timestamp("2026-08-22"),
        max_contact_count: int = 100,
    ) -> None:
        """Initialize CleaningPipeline with configuration thresholds.

        Args:
            reference_date: Reference cutoff timestamp for future date detection.
            max_contact_count: Upper bound threshold for valid customer touchpoints.
        """
        self.reference_date = reference_date
        self.max_contact_count = max_contact_count
        self.date_validator = DateValidator(reference_cutoff=reference_date)
        self.category_normalizer = CategoryNormalizer()

    def _normalize_text_columns(self, df: pd.DataFrame) -> pd.DataFrame:
        """Trim leading/trailing whitespace and collapse internal spaces across all string columns."""
        df_out = df.copy()
        for col in df_out.columns:
            if df_out[col].dtype == object:
                df_out[col] = (
                    df_out[col]
                    .fillna("")
                    .astype(str)
                    .str.strip()
                    .str.replace(r"\s+", " ", regex=True)
                )
        return df_out

    def _clean_triaged_flag(self, df: pd.DataFrame) -> pd.DataFrame:
        """Standardize the 'triaged' boolean flag."""
        df_out = df.copy()
        if "triaged" not in df_out.columns:
            df_out["triaged"] = False
            return df_out

        truthy = {"yes", "y", "true", "1"}
        falsy = {"no", "n", "false", "0"}

        clean_flags = []
        for _, row in df_out.iterrows():
            val = str(row["triaged"]).strip().lower()
            triage_date_val = str(row.get("triage_date", "")).strip()

            if val in truthy:
                clean_flags.append(True)
            elif val in falsy:
                clean_flags.append(False)
            elif triage_date_val != "" and triage_date_val.lower() not in ("nan", "none", "nat"):
                clean_flags.append(True)
            else:
                clean_flags.append(False)

        df_out["triaged"] = clean_flags
        return df_out

    def _clean_contact_counts(self, df: pd.DataFrame) -> Tuple[pd.DataFrame, int]:
        """Sanitize contact counts by imputing negatives and capping extreme spam outliers."""
        df_out = df.copy()
        mod_count = 0
        if "contact_count" not in df_out.columns:
            return df_out, mod_count

        numeric_contacts = pd.to_numeric(df_out["contact_count"], errors="coerce")
        # Compute median of valid contact counts (0 to max_contact_count)
        valid_mask = numeric_contacts.notna() & (numeric_contacts >= 0) & (numeric_contacts <= self.max_contact_count)
        median_contact = int(numeric_contacts[valid_mask].median()) if valid_mask.any() else 3

        cleaned_contacts: List[int] = []
        for val in numeric_contacts:
            if pd.isna(val) or val < 0 or val > self.max_contact_count:
                cleaned_contacts.append(median_contact)
                mod_count += 1
            else:
                cleaned_contacts.append(int(val))

        df_out["contact_count"] = cleaned_contacts
        return df_out, mod_count

    def clean(self, raw_df: pd.DataFrame) -> CleaningPipelineResult:
        """Execute the deterministic, multi-stage cleaning pipeline on raw data.

        Args:
            raw_df: Untouched raw input DataFrame.

        Returns:
            CleaningPipelineResult: Structured results including cleaned and quarantined datasets.
        """
        initial_rows = len(raw_df)
        logger.info(f"Initiating cleaning pipeline for {initial_rows} raw records...")

        # Stage 1: Text whitespace normalization
        df_stage1 = self._normalize_text_columns(raw_df)

        # Stage 2: Category, Priority, and Status standardization
        df_stage2, norm_records = normalize_categories(df_stage1)
        modifications_count = sum(1 for r in norm_records if r.was_modified)

        # Stage 3: Standardize Triaged flag
        df_stage3 = self._clean_triaged_flag(df_stage2)

        # Stage 4: Sanitize contact counts
        df_stage4, contact_mods = self._clean_contact_counts(df_stage3)
        modifications_count += contact_mods

        # Stage 5: Date validation & Duration computation
        parsed_intakes: List[Optional[str]] = []
        parsed_closures: List[Optional[str]] = []
        parsed_triages: List[Optional[str]] = []
        duration_list: List[Optional[float]] = []
        quarantine_mask: List[bool] = []
        quarantine_reasons: List[str] = []

        for idx, row in df_stage4.iterrows():
            case_id = str(row.get("case_id", "")).strip()
            # Primary Key validation
            if not case_id or case_id.lower() in ("nan", "none", "null"):
                quarantine_mask.append(True)
                quarantine_reasons.append("Missing primary key `case_id`")
                parsed_intakes.append(None)
                parsed_closures.append(None)
                parsed_triages.append(None)
                duration_list.append(None)
                continue

            # Date validation
            date_res = self.date_validator.validate_record(
                row_index=int(idx),
                intake_str=row.get("intake_date", None),
                closure_str=row.get("closure_date", None),
                triage_str=row.get("triage_date", None),
            )

            # Check critical date errors that require record quarantine
            critical_errors = [
                f for f in date_res.error_flags
                if f in ("INVALID_INTAKE_FORMAT", "INVALID_CLOSURE_FORMAT", "FUTURE_INTAKE_DATE", "NEGATIVE_DURATION")
            ]

            if critical_errors:
                quarantine_mask.append(True)
                quarantine_reasons.append(f"Critical date anomaly: {', '.join(critical_errors)}")
                parsed_intakes.append(None)
                parsed_closures.append(None)
                parsed_triages.append(None)
                duration_list.append(None)
            else:
                quarantine_mask.append(False)
                quarantine_reasons.append("")
                parsed_intakes.append(
                    date_res.parsed_intake.strftime("%Y-%m-%d") if date_res.parsed_intake else None
                )
                parsed_closures.append(
                    date_res.parsed_closure.strftime("%Y-%m-%d") if date_res.parsed_closure else None
                )
                parsed_triages.append(
                    date_res.parsed_triage.strftime("%Y-%m-%d") if date_res.parsed_triage else None
                )
                duration_list.append(date_res.duration_days)

        df_stage4["intake_date"] = parsed_intakes
        df_stage4["closure_date"] = parsed_closures
        df_stage4["triage_date"] = parsed_triages
        df_stage4["duration_days"] = duration_list
        df_stage4["quarantine_reason"] = quarantine_reasons

        # Stage 6: Separate Quarantined vs Clean Cohort
        quarantined_df = df_stage4[quarantine_mask].copy()
        clean_candidates = df_stage4[~np.array(quarantine_mask)].copy()

        # Stage 7: Deduplication (Keep first occurrence of exact and normalized duplicates)
        dedupe_subset = ["client_name", "category", "intake_date", "closure_date"]
        # Normalize for deduplication comparison
        dedupe_keys = clean_candidates[dedupe_subset].apply(
            lambda col: col.astype(str).str.lower().str.strip()
        )
        is_duplicate = dedupe_keys.duplicated(keep="first")
        deduplicated_count = int(is_duplicate.sum())

        cleaned_df = clean_candidates[~is_duplicate].copy()
        cleaned_df.drop(columns=["quarantine_reason"], inplace=True, errors="ignore")
        cleaned_df.reset_index(drop=True, inplace=True)

        final_rows = len(cleaned_df)
        quarantined_count = len(quarantined_df)

        logger.info(
            f"Cleaning pipeline execution completed successfully:\n"
            f"  - Initial Raw Records: {initial_rows}\n"
            f"  - Quarantined Records: {quarantined_count}\n"
            f"  - Deduplicated Redundant Records: {deduplicated_count}\n"
            f"  - Clean Analytical Records: {final_rows}\n"
            f"  - Modifications Applied: {modifications_count}"
        )

        return CleaningPipelineResult(
            cleaned_df=cleaned_df,
            quarantined_df=quarantined_df,
            initial_rows=initial_rows,
            final_rows=final_rows,
            deduplicated_rows_count=deduplicated_count,
            quarantined_rows_count=quarantined_count,
            modifications_applied=modifications_count,
        )


def run_cleaning_pipeline(
    raw_path: Union[str, Path] = "data/raw/case_management_raw.csv",
    output_cleaned_path: Union[str, Path] = "data/cleaned/case_management_cleaned.csv",
    raw_df: Optional[pd.DataFrame] = None,
) -> CleaningPipelineResult:
    """Execute cleaning pipeline and save standardized output CSV.

    Args:
        raw_path: Input path to raw CSV file.
        output_cleaned_path: Target path to save cleaned analytical dataset.
        raw_df: Optional pre-loaded DataFrame.

    Returns:
        CleaningPipelineResult: Cleaning summary and DataFrames.
    """
    if raw_df is None:
        from src.data.load_data import load_raw_data

        raw_df = load_raw_data(raw_path)

    pipeline = CleaningPipeline()
    result = pipeline.clean(raw_df)

    out_file = Path(output_cleaned_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    result.cleaned_df.to_csv(out_file, index=False, encoding="utf-8")
    logger.info(f"Saved cleaned analytical dataset to: {out_file.resolve()}")

    return result
